# Generated by Django 5.2.4 on 2025-09-16 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='section',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
