# Generated by Django 5.2.4 on 2025-09-16 18:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_section_pdf_file_alter_section_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
