# Generated by Django 5.2.4 on 2025-08-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='photo',
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='test_photos/'),
        ),
    ]
