


POST https://web-0bben6p5dii9.up-de-fra1-k8s-1.apps.run-on-seenode.com/api/register/
Content-Type: application/json

{
    "username":"joo_hamzy",
    "email":" youssifhamdy3@gmail.com",
    "password":"12345678y",
    "password_confirm":"12345678y",
    "first_name":"joo",
    "last_name":"elh"
}


###


POST https://web-0bben6p5dii9.up-de-fra1-k8s-1.apps.run-on-seenode.com/api/verify-email/0c4f53d1-6a9a-4a4a-9f1d-62a4e87b0047/

Content-Type: application/json

{
    
}

###

POST https://web-0bben6p5dii9.up-de-fra1-k8s-1.apps.run-on-seenode.com/api/login/

{
    "username_or_email":"joo_hamzy",
    "password":"12345678y"
}


###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json
# Authorization: 

{
    "username_or_email":"joo_hamzy",
    "password":"12345678y"
}


###

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json
# Authorization: 

{
    "username":"jii",
    "email": "youss49233@gmail.com",
    "password":"12345678y",
    "password_confirm":"12345678y",
    "first_name":"omar",
    "last_name":"sanad"
}