


POST  educational-platform-git-main-youssefs-projects-e2c35ebf.vercel.app/user/register/
Content-Type: application/json

{
    "username":"joooooo",
    "email":" youssefabdelallem23@gmail.com",
    "password":"12345678y",
    "password_confirm":"12345678y",
    "first_name":"joo",
    "last_name":"elh",
    "user_type":"admin",
    "phone_number":"0123456789",
    "date_of_birth":"2000-01-01"
}


###

POST  https://educational-platform-git-main-youssefs-projects-e2c35ebf.vercel.app/user/resend-verification-email/
Content-Type: application/json

{
    "email": "youss4923@gmail.com"
}

###

POST https://web-0bben6p5dii9.up-de-fra1-k8s-1.apps.run-on-seenode.com/api/verify-email/0c4f53d1-6a9a-4a4a-9f1d-62a4e87b0047/

Content-Type: application/json

{
    
}

###

POST https://educational-platform-md062b9uy-youssefs-projects-e2c35ebf.vercel.app/user/delete-account/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MzMwMDI4LCJpYXQiOjE3NTYzMjk3MjgsImp0aSI6IjNkODkxNjY1MjYxYjRiYjRiZDJlZTIwZDc1MGI2MzQ1IiwidXNlcl9pZCI6IjIyIn0.pAhW4WRxuppUe3KmUELv7TBG2i2WStnj4FxUGVc9t5U


###

POST https://educational-platform-md062b9uy-youssefs-projects-e2c35ebf.vercel.app/user/login/
Content-Type: application/json

{
    "username_or_email":"joo_hamzy",
    "password":"12345678y"
}

###

POST https://web-0bben6p5dii9.up-de-fra1-k8s-1.apps.run-on-seenode.com/api/change-password/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTYzNDQzLCJpYXQiOjE3NTU5NjMxNDMsImp0aSI6IjUyMjA5OTk0YjdhYzQ5OWVhYTY3N2JiZDRiMDhmMDI3IiwidXNlcl9pZCI6IjcifQ.I-mWOgormZiJh5aBGyGtSZ004gKu349BScGG22K9Io8

{
    "old_password": "elhamzy111",
    "new_password": "elhamzy222",
    "new_password_confirm": "elhamzy222"
}

###

POST https://web-0bben6p5dii9.up-de-fra1-k8s-1.apps.run-on-seenode.com/api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTYzNDQzLCJpYXQiOjE3NTU5NjMxNDMsImp0aSI6IjUyMjA5OTk0YjdhYzQ5OWVhYTY3N2JiZDRiMDhmMDI3IiwidXNlcl9pZCI6IjcifQ.I-mWOgormZiJh5aBGyGtSZ004gKu349BScGG22K9Io8





###

GET https://educational-platform-qg3zn6tpl-youssefs-projects-e2c35ebf.vercel.app/user/profile/parent/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MjI0MDQwLCJpYXQiOjE3NTYyMjM3NDAsImp0aSI6ImVhZDdlMmYzNDc5NzQ3ZjY5MDExY2YyYjQxNjQxMDhmIiwidXNlcl9pZCI6IjIyIn0.8Kq5vcFAUCxdmSMYn8-7f1D6OJ2qMCUVdOSZKldlTFI


###

POST http://127.0.0.1:8000/user/login/
Content-Type: application/json

{
    "username_or_email": "youss4923@gmail.com",
    "password": "youss4923"
}

###

POST https://educational-platform-qg3zn6tpl-youssefs-projects-e2c35ebf.vercel.app/user/link-child/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MjI0MDQwLCJpYXQiOjE3NTYyMjM3NDAsImp0aSI6ImVhZDdlMmYzNDc5NzQ3ZjY5MDExY2YyYjQxNjQxMDhmIiwidXNlcl9pZCI6IjIyIn0.8Kq5vcFAUCxdmSMYn8-7f1D6OJ2qMCUVdOSZKldlTFI


{
    "child_username": "test_link"
}



###

POST http://127.0.0.1:8000/user/delete-account/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MzI5NDUzLCJpYXQiOjE3NTYzMjkxNTMsImp0aSI6Ijg4MGY2YjdmMWVhNjQyYTQ4ODUzMGZhMmQ3MWZhNTU2IiwidXNlcl9pZCI6IjI1In0.027V1QSYNzTkIa2WqH3fEgr8RoxDJGXCn66aQFZI_6k



###

POST  http://127.0.0.1:8000/user/login/
Content-Type: application/json

{
    "username_or_email": "hamzzy",
    "password": "12345678y"
}
###

# {   
#     "username":"hamzzyy",
#     "email":" youssifhamdy333@gmail.com",
#     "password":"12345678y",
#     "password_confirm":"12345678y",
#     "first_name":"joo",
#     "last_name":"elfess",
#     "user_type":"student",
#     "phone_number":"0123456789",
#     "parent": "joo_hamzy"

# }


###

POST http://127.0.0.1:8000/user/delete-account/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MzI4NzUyLCJpYXQiOjE3NTYzMjg0NTIsImp0aSI6IjA5ZWMzMzNjNTgzZjQ4YmI4MjRhYzM0OTJlMGIyOTI2IiwidXNlcl9pZCI6IjI4In0.zrR0jOMP7OLiQqvnV5KFSjQtznVDUCcbEQ3Lak7M8dM



###

GET  http://127.0.0.1:8000/api/profile/parent/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MTI3NjE3LCJpYXQiOjE3NTYxMjczMTcsImp0aSI6IjEyNjZjNGQ5ODkyYzQ1ZjNhZWViZjc5NzY5NzA2YTU4IiwidXNlcl9pZCI6IjIyIn0.JGQ6rX1GY1gg1D2p-Obd0_nVI3IpJLzd9i_7UqXdwM4




###

POST educational-platform-git-main-youssefs-projects-e2c35ebf.vercel.app/user/password-reset/confirm/3805/
Content-Type: application/json
# Authorization: 

{
    "token" :"3805",
    "new_password": "new_password123",
    "new_password_confirm": "new_password123"
}

###

POST http://127.0.0.1:8000/user/password-reset/request/
Content-Type: application/json
# Authorization: 

{
    "email": "youss4923@gmail.com"
}



###

POST http://127.0.0.1:8000/api/change-password/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTYzNzUzLCJpYXQiOjE3NTU5NjM0NTQsImp0aSI6ImI1YjBjZjZmNWU5OTQ2ZDBiMmFiYThkOTI4NDY2Y2UzIiwidXNlcl9pZCI6IjcifQ.WtfSA_6GG3yMP3VpO11cTuUaNfk1pPjvHgVoL4WHnMw

{
    "old_password": "elhamzy333",
    "new_password": "elhamzy444",
    "new_password_confirm": "elhamzy444"

}


###

POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTYzNzUzLCJpYXQiOjE3NTU5NjM0NTQsImp0aSI6ImI1YjBjZjZmNWU5OTQ2ZDBiMmFiYThkOTI4NDY2Y2UzIiwidXNlcl9pZCI6IjcifQ.WtfSA_6GG3yMP3VpO11cTuUaNfk1pPjvHgVoL4WHnMw



###

POST http://127.0.0.1:8000/api/link-child/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MTI3NjE3LCJpYXQiOjE3NTYxMjczMTcsImp0aSI6IjEyNjZjNGQ5ODkyYzQ1ZjNhZWViZjc5NzY5NzA2YTU4IiwidXNlcl9pZCI6IjIyIn0.JGQ6rX1GY1gg1D2p-Obd0_nVI3IpJLzd9i_7UqXdwM4


{

    "child_username": "hamzzyy"
}





# from rest_framework.validators import ValidationError
# from django.contrib.auth.password_validation import validate_password
# from rest_framework import serializers
# class change_password(serializers.Serializer):
#     """
#     Serializer for password change
#     """
#     old_password = serializers.CharField(write_only=True)
#     new_password = serializers.CharField(write_only=True, validators=[validate_password])
#     new_password_confirm = serializers.CharField(write_only=True)

#     def validate(self, attrs):
#         if attrs['new_password'] != attrs['new_password_confirm']:
#             raise serializers.ValidationError("New passwords don't match")
#         return attrs

#     def validate_old_password(self, value):
#         user = self.context['request'].user
#         if not user.check_password(value):
#             raise serializers.ValidationError("Old password is incorrect")
#         return value
