# Generated by Django 5.2.4 on 2025-09-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcertificate',
            name='certificate_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
